language: r
sudo: false
cache: packages
r_packages:
- knitr
- covr
- drat
after_success:
- Rscript -e 'library("covr");codecov()'
- test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && bash
  drat.sh
env:
  global:
    secure: KA2xOyjEjKv1+Q5oM1AEe/BW2GVvh/V+dmmreXkEklqqGNrR7q4CgYstbQn9ZjLuESfilNwo9zm5pWa28h8cZfLm6Qdw9IOYFV5naSUS4+Ne9quql6tQNZ1cmU9NEs3Ad/N+9srLx8XX9/i7eVVSufre2fq7Lu96utiAYZ3W4L8=
